import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { motion } from 'framer-motion'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const contentAnimation = {
    hidden:{
      opacity:0
    },
    visible:{
      opacity:1,
      transition:{
        duration:0.2,
        when:"beforeChildren",
        staggerChildren:0.35
      }
    }
  }

  const contentHeading = {
    hidden:{
      y:-60
    },
    visible:{
      y:0,
      transition:{
        duration:0.2,
       
      }
    }
  }

  const btnAnimate={
    hidden:{
      x:"-100vw"
    },
    visible:{
      x:0,
      transition:{
        duration:0.5,
       
      }
    }
  }

  const pAnimate={
    hidden:{
      x:"100vw"
    },
    visible:{
      x:0,
      transition:{
        duration:0.5,
       
      }
    }
  }
  return (
    <>
      <Head>
        <title>Transvet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Header- Logo.jpg" />
      </Head>

      <div className='flex items-center justify-center mt-[0px]'>
        <div className='relative rounded-2xl  w-[430px] '>
        <div className="absolute top-0 left-0">
            <Image src="/Shapes.png" width={250} height={200} alt="vector"/>
          </div>

          <div>
            <Image src="/Vector 1.png" width={450} height={200} alt="vector"/>
          </div>
          <motion.div className='flex items-center justify-center ' >
          <Image src="/undraw_teacher_35j2 1.png" width={250} height={200} alt="vector"/>
          </motion.div>

          <motion.div className='flex flex-col items-center justify-center mt-[40px] p-3 py-4 homeContent' variants={contentAnimation} initial="hidden" animate="visible">
            <motion.h1 className='text-center font-bold text-2xl mb-[20px]' variants={contentHeading}>Transvet</motion.h1>
            <motion.p variants={pAnimate} className='text-center p-2'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At urna, sit consequat luctus et. Quis vitae in blandit nisl, facilisis fermentum. Pharetra consequat scelerisque dapibus nunc amet non ut. Morbi ut eu non quis ipsum.

            </motion.p>
            <div className='flex flex-col items-center justify-center gap-[20px] mt-[20px] '>
            <motion.button className='bg-[#ACB4F8] flex items-center justify-center p-2 w-[300px] font-bold h-[50px]' variants={btnAnimate}>Sign Up</motion.button>
            <motion.button className='bg-[#ACB4F8] flex items-center justify-center p-2 w-[300px] font-bold h-[50px]'  variants={btnAnimate}>Log in</motion.button>
          </div>
          </motion.div>
         

        </div>


      </div>
    
          
          
      
          
    </>
  )
}
