import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { motion } from 'framer-motion'
import Button from "./button"
import Link from "next/link"
import {useState} from "react"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

 

  const contentAnimation = {
    hidden:{
      opacity:0
    },
    visible:{
      opacity:1,
      transition:{
        duration:0.2,
        when:"beforeChildren",
        staggerChildren:0.35
      }
    }
  }

  const contentHeading = {
    hidden:{
      y:-60
    },
    visible:{
      y:0,
      transition:{
        duration:0.2,
       
      }
    }
  }

  const btnAnimate={
    hidden:{
      x:"-100vw"
    },
    visible:{
      x:0,
      transition:{
        duration:0.5,
       
      }
    }
  }

  const pAnimate={
    hidden:{
      x:"100vw"
    },
    visible:{
      x:0,
      transition:{
        duration:0.5,
       
      }
    }
  }
  return (
    <>
      <Head>
        <title>Transvet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Header- Logo.jpg" />
      </Head>

      <div className='items-center justify-center flex flex-col h-[100vh] '>

        <div className='HomeContainer flex flex-col items-center justify-center'>
          <div className='relative TopHeader'>
            <div className='absolute -top-[60px] left-0 right-0'>
            <Image src="/Shapes.png" width={250} height={200} alt="bannerImage"/>
            </div>
            <div className='w-full ' style={{marginTop:'-50px'}}>
              <Image src="/Vector 1.png" width={450} height={200} alt="bannerImage"/>

            </div>
            <div className='ImagePerson absolute top-[250px] left-[30px]'>
          <Image src="/undraw_teacher_35j2 1.png" width={300} height={200} alt="bannerImage"/>
          </div>
          </div>

          <div className='Heading'>
            <h1 className='font-bold text-2xl'>Transvet</h1>

          </div>

          <div className='para p-2 flex flex-col items-center justify-center'>
          <motion.p className="text-center text-sm p-2">Transvet, take your audio and written words and translate into different languages of choice from different countries.</motion.p>
          <br/><motion.span className='font-extrabold text-center' initial={{opacity:0,scale:3}} animate={{opacity:1,scale:1}} transition={{duration:0.4,delay:0.3,type:"spring"}}>Get Started Now.</motion.span>
          </div>
<div>
  <Button/>
</div>
        

         
        </div>


      </div>
    
          
          
      
          
    </>
  )
}
